# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]

#################################################################

vps = session.viewports[session.currentViewportName]
vpname = vps.name
modelName = session.sessionState[session.currentViewportName]['modelName']

#################################################################
	
amps = mdb.models[modelName].amplitudes.keys()

xamps = ['(default)']

if len(amps) > 0:
	for x in amps:
		try:
			xamps.append(x)
		except:
			pass

defaultamp = xamps[0]

################################################################

mysteps = mdb.models[modelName].steps.keys()

xsteps = []
for x in mysteps:
	try:
		xsteps.append(x)
	except:
		pass
	
defaultstep = vps.assemblyDisplay.step

if len(xsteps) > 1:
	xsteps.remove('Initial')
	if defaultstep == 'Initial':
		defaultstep = xsteps[0]

#################################################################


dialogBox = RsgDialog(title='Create Surface Force', kernelModule='createTracForce_kernel', kernelFunction='createForce', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Base Data', layout='LAYOUT_FILL_X')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=21, labelText='Name:  ', keyword='kw_name', default='SurfForce')

#################################################################

RsgComboBox(name='ComboBox_1', p='GroupBox_1', text='Step:     ', keyword='kw_step', default=defaultstep, comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')

for x in xsteps:
	RsgListItem(p='ComboBox_1', text=x)

#RsgComboBox(name='ComboBox_1', p='GroupBox_1', text='Step:     ', keyword='kw_step', default='Step-1234', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
#RsgListItem(p='ComboBox_1', text='Item 1')
#RsgListItem(p='ComboBox_1', text='Item 2')
#RsgListItem(p='ComboBox_1', text='Item 3')


#################################################################

RsgPickButton(p='GroupBox_1', text='Select Face(s):  ', keyword='kw_faces', prompt='Select face(s) and confirm', entitiesToPick='MDB_GEOMETRY|FACES', numberToPick='MANY')
RsgGroupBox(name='GroupBox_2', p='DialogBox', text='Force Components', layout='LAYOUT_FILL_X')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=15, labelText='F1:  ', keyword='kw_fx', default='0')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=15, labelText='F2:  ', keyword='kw_fy', default='0')
RsgTextField(p='GroupBox_2', fieldType='Float', ncols=15, labelText='F3:  ', keyword='kw_fz', default='0')
RsgGroupBox(name='GroupBox_3', p='DialogBox', text='Optional Data', layout='LAYOUT_FILL_X')

#################################################################

RsgComboBox(name='ComboBox_2', p='GroupBox_3', text='Amplitude:   ', keyword='kw_amplitude', default='(default)', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')

for x in xamps:
	RsgListItem(p='ComboBox_2', text=x)
	
#RsgComboBox(name='ComboBox_2', p='GroupBox_3', text='Amplitude:   ', keyword='kw_amplitude', default='(default)', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
#RsgListItem(p='ComboBox_2', text='Item 1')
#RsgListItem(p='ComboBox_2', text='Item 2')
#RsgListItem(p='ComboBox_2', text='Item 3')

#################################################################

RsgPickButton(p='GroupBox_3', text='Local CSYS:  ', keyword='kw_csys', prompt='Select CSYS and confirm', entitiesToPick='MDB_GEOMETRY|DATUM_CSYS', numberToPick='ONE')
RsgCheckButton(p='GroupBox_3', text='Follow rotation', keyword='kw_rotation', default=True)
RsgCheckButton(p='GroupBox_3', text='Update area with deformation', keyword='kw_update', default=True)
dialogBox.show()